# **🔢 Numpy**
  The NumPy library is the core library for scientific computing in Python. It provides a  high-performance multidimensional array object, and tools for working with these arrays.  

In [1]:
#importing numpy
import numpy as np


if you want to add elements of two lists together like [1, 2, 3] + [1, 2, 3] = [2, 4, 6], doing this with regular lists will not works, the two lists will be concatenated not added mathimatically -- that's why we have Numpy, we can implement a huge number of mathematics operations on lists with Numpy!

In [ ]:
list1 = [1, 2, 3]
addition = list1 + list1  # wrong way to add two lists
addition

[1, 2, 3, 1, 2, 3]

In [ ]:
list1 = np.array([1, 2, 3])
list2 = np.array([1, 1, 1])
addition = list1 + list2  # right way to add two lists
addition

array([2, 3, 4])

**Creating arrays in numpy**

In [ ]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
a = np.zeros((2, 3), dtype=np.int16)
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [ ]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

- What is the difference between '*arange*' and '*linespace*' ?

 =**np.arange:** generates values with a specified step size.

 =**np.linspace:** generates a specified number of evenly spaced values between two endpoints.

In [ ]:
a = np.arange(5, 25, 5)
a

array([ 5, 10, 15, 20])

In [ ]:
a = np.linspace(0, 10, 5)  #step = stop - start / elements - 1
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
a = np.full((2,2),7) # constant array
a

array([[7, 7],
       [7, 7]])

In [ ]:
a =np.identity(n = 3) # identity matrix
# a =np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

How to create an array with random numbers?

1.   **np.random.rand(x, y):** randoms uniformly distributed between 0 and 1
2. **np.random.randint(start, stop, size = (x, y)):** random integers
3.   **np.random.uniform(start, stop, size = (x, y)):** random floats



In [18]:
np.random.seed(77)
a = np.random.rand(2,2)
a

array([[0.91910903, 0.6421956 ],
       [0.75371223, 0.13931457]])

In [ ]:
a = np.random.randint(1,11, size = (2,2))
a

array([[ 1, 10],
       [ 8,  6]])

In [ ]:
a = np.random.uniform(1,10, size = (2,2))
a

array([[3.93535843, 5.86961039],
       [3.16211658, 5.90880633]])

**Creating 2D arrays**

In [ ]:
a_2d = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])
a_2d

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
a_2d.ndim

2

In [ ]:
a_2d.shape

(4, 3)

In [ ]:
a_2d.size

12

In [22]:
a_2d = np.arange(5, 25, 5).reshape(2,2)  # num of elements = stop - start / step
a_2d

array([[ 5, 10],
       [15, 20]])

In [ ]:
a_2d = np.linspace(0, 1, 10).reshape(2,5)
a_2d

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444],
       [0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]])

*Note that: methods like zeros and ones already takes dimenions so we do not need to use reshape with them*


**Arithmetic Operations**

In [ ]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

In [ ]:
res = np.add(a , b) #  or a + b
res

array([ 3,  7, 11, 15])

In [ ]:
res = np.subtract(a , b) #  or a - b
res

array([1, 1, 1, 1])

In [ ]:
res = np.divide(a , b) #  or a / b
res

array([2.        , 1.33333333, 1.2       , 1.14285714])

In [ ]:
res = np.multiply(a , b) #  or a * b
res

array([ 2, 12, 30, 56])

In [ ]:
res = np.power(b, 2) # or b ** 2
res

array([ 1,  9, 25, 49])

In [ ]:
res = np.power(b, a)
res

array([      1,      81,   15625, 5764801])

In [ ]:
x = [25, 9, 36]
res = np.sqrt(x)
res

array([5., 3., 6.])

In [ ]:
res = np.dot(a, b)
res

np.int64(100)

**Conditional Arithmetic**

In [ ]:
a = np.array([10, 15, 20, 25])
a[a>15] += 5
a

array([10, 15, 25, 30])

**Comparison Operations**

In [ ]:
a = np.array([1,2,3])
b = np.array([1,1,1])
a == b

array([ True, False, False])

In [ ]:
np.array_equal(a, b)

False

In [ ]:
a != b

array([False,  True,  True])

In [ ]:
a > b

array([False,  True,  True])

**Access Items in numpy arrays**

In [ ]:
a = np.array([10, 20, 30, 40])

In [ ]:
a[1] # access one item

np.int64(20)

In [ ]:
a[1:3] # access more than one sequential item using slicing

array([20, 30])

In [ ]:
a[::2] # access non-sequential items by defining step in slicing

array([10, 30])

In [ ]:
a[[0, 3, 2]] #access more than one item that are not sequential by their indexes using fancy indexing

array([10, 40, 30])

In [28]:
# Bolean indexing, example: even elements
x = np.array([1, 2, 3, 4])
bool_mask = x%2 == 0
x[bool_mask]

array([2, 4])

**Acessing 2d arrays**

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
a[1][1]

np.int64(5)

In [ ]:
a[: , -2:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
a[:,0]

array([1, 4, 7])

In [ ]:
a[1, 0]

np.int64(4)

In [ ]:
a[1][0] #same as a[1, 0]

np.int64(4)

In [ ]:
a[:2, 1:]  # access by slicing

array([[2, 3],
       [5, 6]])

In [ ]:
a[0 , 1:] # access by slicing

array([2, 3])

**Exercise 1: "Hot Day Finder"**

Tasks:

- Create a 4×7 matrix of random floats between 20 and 40 representing weekly temperatures for a month (4 weeks × 7 days).



- Create an array called weekdays containing day names in order:
['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']



- Use slicing to extract the last week's temperatures (last row of the matrix).

- Create a boolean mask identifying days where temperature exceeded 25°C in the last week.

- Apply this mask to the weekdays array to get names of hot days.


In [ ]:
month = np.random.uniform(20, 40, size = (4, 7))
last_week = month[-1, :]
condition = last_week > 25
week_days = np.array(['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])
hot_days = week_days[condition]
hot_days

array(['Saturday', 'Monday', 'Tuesday', 'Thursday'], dtype='<U9')

In [ ]:
last_week = month[-1, :]


In [ ]:
condition = last_week > 25
condition

array([ True, False,  True,  True, False,  True, False])

In [ ]:
week_days = np.array(['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])
hot_days = week_days[condition]
hot_days

array(['Saturday', 'Monday', 'Tuesday', 'Thursday'], dtype='<U9')

**Array Manipulation**

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2],
              [3, 4]])


In [ ]:
a = np.append(a,5) # add a new element
a

array([1, 2, 3, 4, 5])

In [ ]:
b = np.append(b, [[5, 6]], axis =0 )
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b = np.append(b, [[0], [0], [0]], axis=1)
b

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 0]])

In [ ]:
a = np.insert(a,2,0) # add a new element in specific position > inseet(index, element)
a

array([1, 2, 0, 3, 4, 5])

In [ ]:
a = np.delete(a, 2)
a

array([1, 2, 3, 4, 5])

what is the difference between resize and reshape?
> reshape does not change the data, if the elements of the new shape is larger or smaller than the original elements, an error will occur. but resize handle this.

In [ ]:
x= np.array([1, 2, 3, 4])
x=  np.resize(x, (2, 3))
x

array([[1, 2, 3],
       [4, 1, 2]])

The flatten() method in NumPy is used to convert a multi-dimensional array into a 1D array.

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a = a.flatten()
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a,b),axis=0)
c

array([1, 2, 3, 4])

**Aggregation Functions**

In [ ]:
a = np.array([0, 10, 30, 50, 10])
av = np.mean(a)
av

np.float64(20.0)

In [ ]:
med = np.median(a)
med

np.float64(10.0)

In [ ]:
standard = np.std(a)
standard

np.float64(17.88854381999832)

In [ ]:
total = np.sum(a)
total

np.int64(100)

In [ ]:
min = np.min(a)
min

np.int64(0)

In [ ]:
max = np.max(a)
max

np.int64(50)

In [ ]:
imin = np.argmin(a)
imin

np.int64(0)

In [ ]:
imax = np.argmax(a)
imax

np.int64(3)

**Conditions Using where**

**np.where():** It returns indices where a condition is True, or it can be used to choose values based on a condition (like an if-else for arrays).

In [ ]:
a = np.array([10, 20, 30, 40, 50])
indices = np.where(a > 25)

print(indices)
print(a[indices])
a[0]

(array([2, 3, 4]),)
[30 40 50]


np.int64(10)

In [ ]:
booll =a < 30
a[booll]

array([10, 20])

In [ ]:
b = np.array([1, 2, 3, 4, 5])
result = np.where(b % 2 == 0, 'even', 'odd')
print(result)

['odd' 'even' 'odd' 'even' 'odd']


**Excercise 2: Sales Data Analysis**
- Create a 4×7 array of random sales between $100 and $500.

- Apply a 10% tax to sales exceeding $300. (x1.10)

- Use np.where() to give a 5% discount to sales below $200. (x 0.95)

- Find the average sales for weekends (last 2 columns).

- Identify days with sales > $400 (boolean mask).




In [ ]:
sales = np.random.uniform(100,500, size=(4,7))
sales

array([[241.29803925, 254.28146325, 278.22236401, 490.82106457,
        391.75760362, 224.89402333, 457.90209572],
       [413.30943807, 204.80013653, 223.79327446, 151.78025191,
        268.86854249, 475.90601399, 246.81714926],
       [273.90998907, 466.83742174, 478.9175684 , 201.90917924,
        383.8814312 , 119.99056194, 153.89757225],
       [302.60237724, 335.62883882, 230.75944346, 157.92577929,
        203.05539615, 442.97835536, 373.58950082]])

In [ ]:
sales[sales > 300] *= 1.10
sales= np.where(sales < 200, sales*0.95, sales)
weekend = sales[:, -2:]
avg = np.mean(weekend)
print(avg)

381.08070303551426


In [ ]:
sales[sales >400]

array([653.28283695, 521.42937042, 609.4676894 , 550.11486207,
       633.43090462, 621.36060834, 637.43928354, 510.94618493,
       402.76376411, 446.72198447, 589.60419098, 497.24762559])